# Generated by Django 3.2.7 on 2022-08-27 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('telephone_mobile', models.CharField(max_length=50)),
                ('type_client', models.CharField(choices=[('Client', 'Client'), ('Partenaire', 'Partenaire')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvenementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('Marriage', 'Marriage'), ('Anniversaire', 'Anniversaire'), ('Fiançailles', 'Fiançailles'), ('Réunion de famille ou amis', 'Réunion de famille ou amis'), ('Soirée à thème', 'Soirée à thème'), ('Soutenance', 'Soutenance'), ('Conférence', 'Conférence'), ('Autre', 'Autre')], max_length=200)),
                ('nombre_invites', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('ville', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(choices=[('Animation musicale', 'Animation musicale'), ('Photos et vidéos', 'Photos et vidéos'), ('Beauté et coiffure', 'Beauté et coiffure'), ('Location de matériel', 'Location de matériel'), ('Traiteur', 'Traiteur'), ('Location de salles', 'Location de salles')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('evenement_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.evenementclient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='MessageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profil_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientprofile')),
                ('service_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serviceevenement')),
            ],
        ),
        migrations.CreateModel(
            name='ImageServicePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service_partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicepartenaire')),
            ],
        ),
    ]
