# Generated by Django 3.2.4 on 2022-09-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageservice',
            name='profil_client',
        ),
        migrations.AddField(
            model_name='messageservice',
            name='message_receiver',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='app.clientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageservice',
            name='message_sender',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='app.clientprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=200),
        ),
    ]
