# Generated by Django 4.0.3 on 2022-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementclient',
            name='evenement',
        ),
        migrations.AddField(
            model_name='evenementclient',
            name='type_evenement',
            field=models.CharField(choices=[('Marriage', 'Marriage'), ('Anniversaire', 'Anniversaire'), ('Fiançailles', 'Fiançailles'), ('Réunion de famille ou amis', 'Réunion de famille ou amis'), ('Soirée à thème', 'Soirée à thème'), ('Soutenance', 'Soutenance'), ('Conférence', 'Conférence'), ('Autre', 'Autre')], default='Mariage', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(choices=[('Animation musicale', 'Animation musicale'), ('Photos et vidéos', 'Photos et vidéos'), ('Beauté et coiffure', 'Beauté et coiffure'), ('Location de matériel', 'Location de matériel'), ('Traiteur', 'Traiteur'), ('Location de salles', 'Location de salles')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
    ]
