# Generated by Django 4.0.3 on 2022-08-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_evenementclient_evenement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementclient',
            name='ville',
            field=models.CharField(max_length=200),
        ),
    ]
