# Generated by Django 4.0.3 on 2022-08-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_evenementclient_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementclient',
            name='description',
        ),
    ]
